apiVersion: v1
kind: Service
metadata:
  labels:
    app: server-python
  name: server-python
spec:
  ports:
    - port: 8099
      protocol: TCP
      targetPort: 8099
  selector:
    app: server-python
  type: NodePort
